modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/nanite/Bamboo-Everything/issues"
license = "All rights reserved"

[[mods]]
modId = "bambooeverything"
version = "${version}"
displayName = "Bamboo Everything"
authors = "Gaz(Gaz492)"
description = '''
All things bamboo
'''
#logoFile = ""

[[dependencies.bambooeverything]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bambooeverything]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bambooeverything]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

#[[mixins]]
#config = "bambooeverything.mixins.json"
